import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
    kotlin("jvm") version "1.6.10"
    id("com.github.johnrengelman.shadow") version "7.1.1"
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://papermc.io/repo/repository/maven-public/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
    mavenCentral()
}

dependencies {
    compileOnly("io.papermc.paper:paper-api:1.17.1-R0.1-SNAPSHOT")
    implementation(kotlin("stdlib"))
}

group = "io.gitlab.user254"
version = "0.0.1-SNAPSHOT"
description = "ParkourPlugin"

java {
    toolchain.languageVersion.set(JavaLanguageVersion.of(16))
}

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

// Custom Task

tasks.register("server") {
    dependsOn("shadowJar")
    doLast {
        exec { commandLine("cp", "build/libs/ParkourPlugin-0.0.1-SNAPSHOT-all.jar", "../../server/plugins/") }
        exec {
            workingDir("../../server/")
            commandLine("/Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home/bin/java", "-Xms512M", "-Xmx2048M", "-jar", "paper-1.18.1.jar", "-nogui")
        }
    }
}

// End Custom Task

val compileKotlin: KotlinCompile by tasks
compileKotlin.kotlinOptions {
    jvmTarget = "16"
}
val compileTestKotlin: KotlinCompile by tasks
compileTestKotlin.kotlinOptions {
    jvmTarget = "16"
}