name: ParkourPlugin

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Check out repository code
        uses: actions/checkout@v2
        
      - name: Setup JDK 16
        run: |
          sudo apt update
          sudo apt install openjdk-16-jdk

      - name: Gradle Build
        run: ./gradlew shadowJar

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          path: build/libs/*.jar
